import { Lead, Client, Engagement, Notification, AuditLog } from '../types';

const now = new Date().toISOString();

export const DUMMY_LEADS: Lead[] = [
  {
    id: 'lead-1',
    companyName: 'TechNova Solutions',
    contactPerson: 'Arjun Mehta',
    ownerName: 'Rahul Sharma',
    ownerContact: '+91-98765-11111',
    email: 'arjun@technova.in',
    phone: '+91-98765-43210',
    industry: 'Technology',
    businessType: 'Pvt. Ltd.',
    leadSource: 'Referral',
    expectedRevenue: 1200000,
    priority: 'HIGH',
    status: 'NEW',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lead-2',
    companyName: 'Apex Manufacturing',
    contactPerson: 'Priya Desai',
    email: 'priya.desai@apex.com',
    phone: '+91-99887-76655',
    industry: 'Manufacturing',
    businessType: 'Public Ltd.',
    leadSource: 'Website',
    expectedRevenue: 2500000,
    priority: 'URGENT',
    status: 'CONTACTED',
    createdAt: now,
    updatedAt: now,
  }
];

export const DUMMY_CLIENTS: Client[] = [
  // ── 5 Business Clients ──────────────────────────────────────────────────
  {
    id: 'client-1',
    companyName: 'Stellar Logistics LLP',
    contactPerson: 'Vikram Singh',
    email: 'vikram@stellarlogistics.com',
    phone: '+91-88776-55443',
    industry: 'Supply Chain & Logistics',
    businessType: 'LLP',
    gstin: '27AABCU9603R1ZX',
    pan: 'AABCU9603R',
    address: '123 Supply Chain Road, BKC, Mumbai',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-2',
    companyName: 'TechNova Solutions Pvt Ltd',
    contactPerson: 'Arjun Mehta',
    email: 'arjun@technova.in',
    phone: '+91-98765-43210',
    industry: 'Technology',
    businessType: 'Pvt. Ltd.',
    gstin: '27AAACT1234F1Z9',
    pan: 'AAACT1234F',
    address: 'Tech Park, Electronic City, Bengaluru',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-3',
    companyName: 'Apex Manufacturing Corp',
    contactPerson: 'Priya Desai',
    email: 'priya.desai@apex.com',
    phone: '+91-99887-76655',
    industry: 'Manufacturing',
    businessType: 'Public Ltd.',
    gstin: '27AAACA5678G1Z2',
    pan: 'AAACA5678G',
    address: 'Industrial Zone, Chakan, Pune',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-4',
    companyName: 'GreenValley Organics Pvt Ltd',
    contactPerson: 'Siddharth Nair',
    email: 'siddharth@greenvalley.co.in',
    phone: '+91-98112-33445',
    industry: 'Retail & E-commerce',
    businessType: 'Pvt. Ltd.',
    gstin: '27AAACG9988H1Z4',
    pan: 'AAACG9988H',
    address: 'Organic Hub, Indiranagar, Bengaluru',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-5',
    companyName: 'Zenith Real Estate Developers',
    contactPerson: 'Karan Malhotra',
    email: 'karan@zenithrealty.in',
    phone: '+91-97654-32109',
    industry: 'Real Estate',
    businessType: 'LLP',
    gstin: '27AAACZ3322J1Z8',
    pan: 'AAACZ3322J',
    address: 'Zenith Towers, Cyber City, Gurugram',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },

  // ── 5 Personal Accounting / Individual Clients ───────────────────────────
  {
    id: 'client-6',
    companyName: 'Dr. Rajesh Sharma (Medical Practice)',
    contactPerson: 'Dr. Rajesh Sharma',
    email: 'dr.rajesh@clinic.in',
    phone: '+91-98200-12345',
    industry: 'Personal Accounting & Taxes',
    businessType: 'Personal Accounting (Individual)',
    gstin: '27AAAPR1234F1Z0',
    pan: 'AAAPR1234F',
    address: 'Clinic #402, Medical Enclave, Pune',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-7',
    companyName: 'Adv. Ananya Deshmukh (Legal Practice)',
    contactPerson: 'Adv. Ananya Deshmukh',
    email: 'ananya@deshmukhlegal.com',
    phone: '+91-98334-55667',
    industry: 'Individual Professional (Doctor/Lawyer/CA)',
    businessType: 'Professional Practice (Doctor / Lawyer / CA)',
    gstin: '',
    pan: 'ABCPD9876E',
    address: 'High Court Chambers, Fort, Mumbai',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-8',
    companyName: 'Vikramaditya Roy (HNI Personal Portfolio)',
    contactPerson: 'Vikramaditya Roy',
    email: 'v.roy@privatewealth.in',
    phone: '+91-99001-88223',
    industry: 'HNI & Personal Wealth',
    businessType: 'HNI / Personal Finance',
    gstin: '',
    pan: 'AJUPR5432K',
    address: 'Penthouse A, Malabar Hill, Mumbai',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-9',
    companyName: 'Rohan Verma (Freelance AI Specialist)',
    contactPerson: 'Rohan Verma',
    email: 'rohan@aiconsulting.dev',
    phone: '+91-97112-99881',
    industry: 'Freelance & Independent Consulting',
    businessType: 'Freelancer / Independent Contractor',
    gstin: '27AABPV6789M1Z1',
    pan: 'AABPV6789M',
    address: 'Co-Work Hub, HSR Layout, Bengaluru',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'client-10',
    companyName: 'Dr. Siddharth Kapoor (Surgeon / Personal Tax)',
    contactPerson: 'Dr. Siddharth Kapoor',
    email: 'siddharth.kapoor@mednet.org',
    phone: '+91-98445-66778',
    industry: 'Personal Accounting & Taxes',
    businessType: 'Individual Taxpayer / Salaried',
    gstin: '',
    pan: 'ASKPK1122L',
    address: 'Bandra West, Mumbai',
    status: 'ACTIVE',
    onboardingDate: now,
    createdAt: now,
    updatedAt: now,
  }
];

export const DUMMY_ENGAGEMENTS: Engagement[] = DUMMY_CLIENTS.map((client, index) => {
  const isBusiness = index < 5;
  const baseFee = isBusiness ? 150000 : 25000;
  return {
    id: `eng-${index + 1}`,
    clientId: client.id,
    clientCompanyName: client.companyName,
    leadId: `lead-${index + 1}`,
    name: isBusiness ? 'Virtual CFO Services' : 'Personal Tax & Accounting',
    status: 'ACTIVE',
    startDate: now,
    services: [
      { id: `svc-${index + 1}`, engagementId: `eng-${index + 1}`, serviceName: isBusiness ? 'Virtual CFO Retainer' : 'Personal Tax Filing', billingCycle: isBusiness ? 'MONTHLY' : 'YEARLY', price: baseFee }
    ],
    documents: [
      { id: `doc-${index + 1}`, engagementId: `eng-${index + 1}`, category: 'FINANCIAL_COMPLIANCE', name: isBusiness ? 'Q1 Balance Sheet' : 'Form 16 / ITR', createdAt: now, status: 'VERIFIED' }
    ],
    tasks: [
      { 
        id: `task-${index + 1}`, 
        engagementId: `eng-${index + 1}`, 
        title: isBusiness ? 'Monthly MIS Preparation' : 'Tax Computation Review', 
        description: 'Prepare details for current period', 
        milestone: 'Initial Setup', 
        estimatedHours: 5, 
        timeSpent: 2, 
        progress: 40, 
        dueDate: now, 
        status: 'IN_PROGRESS', 
        priority: 'HIGH', 
        employeeId: 'u-aarati-employee',
        employeeName: 'Aarati (Employee)',
        reviewPoints: [], 
        createdAt: now, 
        updatedAt: now 
      }
    ],
    compliances: [
      { 
        id: `comp-${index + 1}`, 
        engagementId: `eng-${index + 1}`, 
        type: isBusiness ? 'GST' : 'INCOME_TAX', 
        dueDate: now, 
        status: 'PENDING', 
        responsibleEmployeeId: 'u-aarati-employee',
        responsibleEmployeeName: 'Aarati (Employee)',
        createdAt: now 
      }
    ],
    invoices: [
      { id: `inv-${index + 1}`, invoiceNumber: `INV-2026-${100 + index + 1}`, engagementId: `eng-${index + 1}`, engagementName: isBusiness ? 'Virtual CFO Services' : 'Personal Tax & Accounting', dueDate: now, milestone: isBusiness ? 'Monthly Retainer' : 'Tax Filing Fee', amount: baseFee, gst: baseFee * 0.18, finalAmount: baseFee * 1.18, status: index % 2 === 0 ? 'PAID' : 'SENT', createdAt: now }
    ],
    collections: [],
    reports: [],
    createdAt: now,
    updatedAt: now,
  };
});

export const DUMMY_NOTIFICATIONS: Notification[] = [
  { id: 'notif-1', title: 'New Lead Assigned', message: 'TechNova Solutions has been assigned to you.', type: 'INFO', isRead: false, createdAt: now },
  { id: 'notif-2', title: 'Compliance Due', message: 'GSTR-1 Filing for Stellar Logistics is due tomorrow.', type: 'WARNING', isRead: false, createdAt: now }
];
